import { type Adapter, catalogIndex, instinctSection, joinBlocks } from "./types.js";

/**
 * Codex reads a single `AGENTS.md`, so the catalog is composed into one
 * document: full skill bodies would blow the budget, therefore skills are
 * indexed and the highest-signal guidance is inlined.
 */
export const codexAdapter: Adapter = {
  id: "codex",
  label: "Codex",
  render(input) {
    const stable = input.catalog.skills.filter((skill) => skill.maturity === "stable");
    const sections = stable.slice(0, 12).map((skill) => {
      const excerpt = skill.body.split("\n").slice(0, 12).join("\n");
      return [`### ${skill.name}`, "", skill.description, "", excerpt, ""].join("\n");
    });

    return [
      {
        path: "AGENTS.md",
        content: joinBlocks([
          `# ${input.projectName} — agent instructions`,
          "Generated by ECC. Regenerate with `ecc install codex`.",
          instinctSection(input.instincts),
          input.contextPack,
          "## Working agreements",
          ...sections,
          catalogIndex(input),
        ]),
      },
    ];
  },
};
